services:
  - type: web
    name: reccer-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    runtime: python
    repo: https://github.com/yourusername/reccer-app
    branch: main
    region: oregon
    autoDeploy: true